# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Node.js 18 as the base image for building
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the source code into the container
COPY . .

# Build the TypeScript code
RUN npm run build

# Use a smaller Node.js image to run the application
FROM node:18-alpine AS runner

# Set the working directory
WORKDIR /app

# Copy the built files and node_modules from the builder stage
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

# Expose any necessary ports (if applicable, not specified in the README)
# EXPOSE 3000

# Set the command to run the application
ENTRYPOINT ["node", "dist/index.js"]
